Dockerfile

Got explanation and solution from here: http://blog.cloud66.com/x509-error-when-using-https-inside-a-docker-container/

Fixed 'failed to load system roots and no roots provided' error.

---

integrations/cleverAWS/aws.go
integrations/cleverAWS/aws_test.go

It'd create invalid aws names if the user had a space in their last name.

Fixed bug for aws username generation

---

integrations/github/github.go

This will hopefully over time make who-is-who (and thus pr-notifier) more accurate.

Don't override existing github user names.

---

launch/who-is-who.yml

Updated resource allocations based on metrics from the past week.
Memory across both services and workers was adjusted to accommodate the max usage seen.  Additional head room was given to apps that hit their max-memory.
CPU for services and workers was adjusted differently from one another.  For workers, CPU allocation was set to a value between the 90<sup>th</sup> and 100<sup>th</sup> percentile.  CPU for services, on the other hand, was set to be slightly above their max usage.
The data these changes were based is linked below.  Please take a look to confirm the new values: https://docs.google.com/spreadsheets/d/14ReGEtZz5oCKaQ6frCqtSH_yW8nBsHRO07miJZDjTTo/edit#gid=0
Finally the team name was added to the launch yaml.
This PR was created programmatically and assigned randomly.  Feel …

Updated who-is-who's resource allocations and team name

---

.drone.yml

Context:  https://clever.atlassian.net/browse/INFRA-1577
Refactor so that report-card is invoked via a Publish block;
this lets Drone do the heavy-lifting instead of setting it up locally.
Expected changes:
- ADDED
- A single entry in the "publish" block `report_card: {}` (if this wasn't already present)
- REMOVED
- All "env" block entries related to report-card are removed
- All "script" block entries related to report-card are removed
- MODIFIED
- YAML reformatting/linting (side-effect)
**Please verify by looking at the build logs**
1. Your build ran successfully (all tests and script steps completed)
2. Report card ran successfully (you can see it in the
If you see any errors in the above, please loop @nathanleiby (@n on Slack) into the PR.
Thanks!

Simpler report-card invocation: who-is-who

---

Makefile
db.js
package.json
tests/test-routes.js

Currently https://production--who-is-who.int.clever.com/list/email/ben.rollin@clever.com return objects.  It should return only one.  The happen because cleverbook created a ben.rollin@clever.com object by posting to `/alias/email/ben.rollin@clever.com`, while coffee-matched created a ben.rollin@clever.com object by posting to `/alias/slack/brollin`.  This inadvertently created two brollin objects.
This PR add a fix to make sure that doesn't happen again as well as a unit test to detect regressions.
TODO:

Who-is-who merges objects with the same email address

---

circle.yml

*Risk rating*: 1 clever clover :four_leaf_clover:  
*or* 0.1 oauth deploys :shipit:
So free to merge yourself
After much discussion, it seems worthwhile to enable docker builds on all branches.  It's always been difficult to deploy development branches to dev.  Which is kinda ironic.  Don't you think? It's like ten thousands tests when all you need is a deploy.  It's like breaking the build by merging to master.  Isn't it ironic?  It's a little too ironic.  I really do think.
Once merged, you'll be able to run `ark start Clever/who-is-who -b <branch>` on a whim.  No more "temporary" changes to [circle.yml](https://github.com/Clever/app-view-service/commit/dbcf816fd208ac42b2821b831b0297978dc6526c#diff-29944324a3cbf9f4bd0162dfe3975d88).  After this PR, you'll live in a world free of sudden …

Enabling docker builds on all branches for Clever/who-is-who

---

.gitignore
Makefile
package.json
scripts/sync-users.js

**Jira:**
[SEC-488](https://clever.atlassian.net/browse/SEC-488)
**Overview:**
This change adds a script and a `make` target to sync `who-is-who` users with our Google G Suite directory.
It finds/fixes three conditions:
1) Google users not in who-is-who (error condition - exits).
2) Google users who are not marked `active` in `who-is-who` (updates)
3) Non-google users who are marked `active` in `who-is-who` (updates)
I'm not 100% this belongs here - alternatively I could move to the infra repo if it makes more sense there.
**Testing:**
I've run this with only my `who-is-who` account targeted, and it appears to write the `active` property correctly.
**Roll Out:**
As soon as a I get a +1, I'll run this for all users. I'm planning on using this to automate some aspects of our terraform setup …

Adds script to compare users with Google FTE group, mark as active

---

scripts/sync-users.js

This change adds users to `who-is-who` automatically if they are in the Google `FTE` organization. Only their email is added; the rest of their attributes (github, slack, team, etc.) still need to be configured manually.
I just ran this for the new employees, and it worked.

Automatically add users to who-is-who

---

go-client/client.go

I'd like to have our who-is-who-syncer mark the `active` field correctly (and deprecate the `make sync` task here). This should allow us to write that field.

Adds 'active' field to go-client, for who-is-who-syncer

---

Makefile
circle.yml
go-client/client.go

**Jira:**
https://clever.atlassian.net/browse/INFRA-2749
**Overview:**
Previously, the Go client would sometimes fail an HTTP call (likely due to load on Dynamo backend). This adds retries to the client.
**Testing:**
Added tests to ensure the client builds. haven't yet tested the behavior but plan to enable this in Dapple.
**Roll Out:**
Merge here, then enable in who-is-who consumers

Add retries to go client

---

go-client/client.go

No longer uses anonymous structs.

update go-client pickabot struct

---

launch/who-is-who.yml

**Roll Out:**
The upstreams of `who-is-who` are:
```at 13:53:52 ❯ curl -s -H "X-Client-Version: 2.50.0" -XGET "https://production--catapult.int.clever.com/applications/who-is-who/upstreams" | jq '."who-is-who"' 
[
"aws-cost-notifier",
"who-is-who-syncer",
"bookworm",
"pickabot",
"dapple",
"dp-finalizer"
]
```
I have redeployed `who-is-who-syncer`, `pickabot`, `dapple`, and `dp-finalizer`. I am planning on deleting https://github.com/Clever/bookworm since it is no longer in use. And I am planning on graveyarding [aws-cost-notifier](https://github.com/Clever/aws-cost-notifier).
So all this is left after this is merged is to kill the old stacks.

To no-homepod.

---

launch/who-is-who.yml

Removing this deprecated "channel" field. Alarms will instead go to the default channel for your team.
Please confirm that this looks correct, and then merge it

remove alarm channel

---

.circleci/config.yml
.github/CODEOWNERS
Makefile
go-client/Makefile
go-client/go.mod
go-client/go.sum
launch/who-is-who.yml

Since this service is about identity and roles/attributes of Cleverites, we're passing ownership
from Infra to Security. Infra will continue to use it for use cases such as looking up a user's
Slack name from their Github name for Dapple, but the ownership will be Security.
As a parting gift, I tried to modernize a bit - change the CircleCI base image to Node to better reflect the fact that this is primarily a node repo, add a `go.mod` file, and make sure the Go client is tested on Go 1.16.

Pass ownership to security.

---

launch/who-is-who.yml

**Jira:**
**Overview:**
This removes the noise we see in #oncall-security due to seldomly failing call. Upon successful retry, this error is resolved, hence let us alert only if more than 50% time, who-is-who is failing.
**Testing:**
👁️ 
**Roll Out:**

Tune alert to only alert critically when more than 50%

---

launch/who-is-who.yml

**JIRA:** https://clever.atlassian.net/browse/INFRANG-5111
**Overview:**
In this PR we will migrate all internal single region services in this repo to use app mesh to hybrid state.
After this PR is merged the workers will have both envoy proxy sidecar and other appmesh constructs as well as a loadbalancers. Other services/workers have the option to use either option for making connections.
Eventually all services and workers will be restarted to make it so that all traffic comes through envoy at which point we will migrate this service to mesh_only
**Rollout:**
- monitor cpu and memory
- if upstream is in mesh then restart them so that traffic is sent using envoy

migrate single-region services to app mesh in hybrid state in dev

---

launch/who-is-who.yml

**JIRA:** https://clever.atlassian.net/browse/INFRANG-5113
**Overview:**
In this PR we will migrate all internal single region services in this repo to use app mesh in mesh_only state in **DEV** only. After this PR is merged the services will delete their loadbalancers. Going forward all the load balancing is done by envoy proxy.
An application in mesh can depend on any other application outside the mesh. But an application outside the mesh cannot depend on an application that is mesh_only. Engineers will still be able to access services using the usual URL but now we are going to share a single loadbalancer across all services!
Currently all apps are in hybrid mode which means that they are already using envoy for loadbalancing instead of using ALBs.
For more details on what each field …

migrate single region services to app mesh in mesh_only state in dev

---

launch/who-is-who.yml

**JIRA:** https://clever.atlassian.net/browse/INFRANG-5115
**Overview:**
In this PR we will migrate all internal single region services in this repo to use app mesh in hybrid state in **PROD**. After this PR the service will have both ALB and envoy proxy. 
When an app is in hybrid mode it's upstream can use either *.int.clever.com url or *.prod.mesh to communicate. On deploy if this app's downstream is in hybrid then we will use *.prod.mesh otherwise we will use *.int.clever.com. Eventually all apps will be restarted so that everthing is using envoy for communication. 
For more details on what each field in `mesh_config` means you can read https://app.getguru.com/card/TnAG64Gc/mesh_config-in-launchyml
Similar to other large scale infrastructure changes we expect some issues so if you …

migrate single region services to app mesh in hybrid state in prod

---

.circleci/config.yml
Dockerfile
launch/who-is-who.yml

**JIRA:** https://clever.atlassian.net/browse/INFRANG-5118
**Overview:**
This PR is part of the second cohort of apps that we are migrating from hybrid to mesh_only.
All apps in this cohort are receiving some amount of requests through their ALB which means they pose a higher risk than the previous cohort of apps.
If this app is receiving traffic via the ALB, double check that `setupInternalRoute` is set to true so that routes are setup for lambdas and other clients to access this service once it is mesh_only and ALBs are removed.
If `setupInternalRoute` is not set then check where the requests are coming from before adding it.
https://clever.grafana.net/d/Kyms8kdVz/applications-envoy-alb?orgId=1&from=now-2d&to=now
**Rollout:**
- monitor cpu and memory
- monitor envoy metrics …

migrate services with some alb traffic to mesh_only

---

launch/who-is-who.yml

https://clever.atlassian.net/browse/INFRANG-5475
In Mesh there is no concept of alarm source of Target, ELB and Total as all metrics are coming from envoy sidecar. We are soon going to merge a change which will block CI for applications if source field is present for InternalErrorAlarms and mesh_config for prod set to mesh_only.
You have to review this PR to see that the new alarms make sense. It was hard to script all the different alarm setups we have across services. In most cases I have removed duplicate alarms but you might want to remove some more alarms or keep some deleted alarms.
Merge PR and deploy via dapple.

clean up alarms

---

.eslintrc.yml
storage/dynamodb.js

**Jira:**
**Overview:**
in oncall-security, getting pings about `TypeError`, which is due to queries resulting in no items, and we try to access empty `Item` field on null object data. As documentation for `GetItemOutput` says: `item` is optional on the returned data.
https://docs.aws.amazon.com/en_us/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/modules/getitemoutput.html  
https://app.datadoghq.com/logs?query=service%3Awho-is-who%20env%3Aproduction%20TypeError%20&cols=host%2Cservice&index=&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1694209791295&to_ts=1694468991295&live=true
**Testing:**
roll this out 
**Roll Out:**

add optional chaining to data access

---

launch/who-is-who.yml

https://clever.atlassian.net/browse/INFRANG-6012
Delete the mesh config as we are exiting mesh and this mesh_config is not used anymore.
Currently catapult is using a feature flag in place of this mesh config and the feature flag is set to "alb_only" for this app. Which means this is already running in production
Merge PR and deploy via dapple

remove mesh_config

---

router.js

**Jira:**
https://clever.atlassian.net/browse/SHAPI-1677
**Overview:**
Noticed that Cleverville wasn't loading. Turns out that there are some null values in the response from who-is-who that's causing issues for Cleverville. I had the option to either 1. fix the data issue 2. make the fix in who-is-who so that null values won't be returned 3. make the fix in Cleverville where it filters out null values from who-is-who's response.
I'm not familiar with the source of the data, so option 1 wasn't possible. I also figured option 3 was too shallow since there could be other services that are using who-is-who who would also need to filter out the null values themselves. Returning null values from who-is-who seems to be undesirable, so option 2 felt like the best option.
**Testing:**
before …

Filter out null values from response
